### PR TITLE
these images are at the old path and no longer needed

### PR DESCRIPTION
**Pull request by derp-derp-derp**

### CODE REVIEW

**Comment by BebopTC** [comment]
Unfortunately because of differences between relative path resolution in github's wiki feature and regular repo markdown features, the images need to be duplicated in order to be viewable in both places. we decided to go with that for now so that it is easier to edit and see changed in the repo before pushing live.

I think we should leave these here for now. That said, I'm thinking a new wiki/docs front end that builds these much prettier may be the best route moving forward, similar to what AC wanted to do.

**Comment by derp-derp-derp** [comment]
Ah, interesting. They new ones are showing up here per the other merge, so I think we're good: https://github.com/turtlecoin/turtlecoin-wiki/blob/master/guides/Participating-in-Raindance.md But please let me know if I should update them in the root images directory as well. Thanks!

**Comment by BebopTC** [comment]
When it gets pushed to the wiki, the wiki build system automatically flattens all (but only) the markdown files into the root folder, so the relative references that work when viewing in-repo break in-wiki. I'd like to move off the github wiki pretty soon but for now just duplicating the images is the easy fix; oncea new system is setup it can go away.

Yeah, updating them in both places for now would be great. If you push that to this PR i'll go ahead and merge it then.. thanks!

**Comment by derp-derp-derp** [comment]
all et on that other PR :)

**Pull request closed without merging**
