### PR TITLE
Fixed image for real

### PR DESCRIPTION
**Pull request by Sajo811**
Figured out how to fix the link so that it appears inline without the full link. Rejoice!

### CODE REVIEW

**Comment by Sajo811** [comment]
It seems to show a hyperlinked text of the name after the image according to the rich diff viewer. Ignore this for now I'll try to fix it later.

**Comment by ZedPea** [comment]
I think this will just work for the turtlecoin-wiki repo, at least on the raindance guide it is done like so:

\!\[Raindance Channel\]\(images/raindance/rain1.jpg\)

Not sure if there is any difference between the two syntax's.

**Comment by Sajo811** [comment]
If you click on the image in the raindance guide then check the path on the top, you will see it links to the images folder inside the guides folder.

I think you can either make full links, or make a guides/images/raindance(or trtlbot++, bootstrap etc.) and place the images in those, with the relative links linking to them.

**Comment by ZedPea** [comment]
Oh I didn't notice those images were in a different folder. I'll take your word for it.

**Comment by Sajo811** [comment]
I'll close this for now, try to make a new folder with the images in my fork and submit a PR

**Pull request closed without merging**
