### PR TITLE
Add RainBorg guide - new raindance

### PR DESCRIPTION
**Pull request by SoreGums**
Remove the previous raindance guide from sidebar
Linked to previous raindance guide from RainBorg guide for posterity

### CODE REVIEW

**Comment by SoreGums** [comment]
it? really... shame :P

and yes

**Comment by dh47** [comment]
Is she hot?

**Comment by Sajo811** [comment]
No, she's super cool. @dh47

**Comment by SoreGums** [comment]
here is a link to read the guide as it would appear
https://github.com/SoreGums/turtlecoin-wiki/wiki/RainBorg-Wat-Dat

**Pull request merged**
