### PR TITLE
Guide for TrtlBot++

### PR DESCRIPTION
**Pull request by Sajo811**
Guide on how to register, deposit and tip.

### CODE REVIEW

**Comment by ZedPea** [comment]
Should `For ex, .tip 1 @RockSteady#7588.` be `For example` or `E.g: ` ?

**Comment by Sajo811** [comment]
`For example`

**Comment by ZedPea** [comment]
This should probably be moved into the guides folder, and named with the same convention as the other guides. You could also update _Sidebar.md to point to it so it appears nicely on the wiki.

**Comment by Sajo811** [comment]
Updated that and added pull request for _Sidebar.md

**Comment by SoreGums** [comment]
pretty sure the filename needs to drop the ++ and add a .md ;)

**Comment by ZedPea** [comment]
Great work :)

**Comment by Sajo811** [comment]
Awesome!! Thanks :D

**Pull request merged**
