### PR TITLE
Add developer-docs/resources

### PR DESCRIPTION
**Pull request by ar-x**
Closes https://github.com/turtlecoin/turtlecoin-wiki/issues/131

### CODE REVIEW

**Comment by SoreGums** [comment]
maybe link it in the sidebar under "developer"
also since this is the docs repo maybe "developer" directory is ok?

**Comment by ar-x** [comment]
@SoreGums Done. Does this work?

**Comment by Sajo811** [comment]
`developer/Resources` will just be `Resources`

**Comment by ar-x** [comment]
@Sajo811 Thanks. Fixed.

**Pull request merged**
