### PR TITLE
added screenshot of deposit received

### PR DESCRIPTION
**Pull request by Sajo811**

### CODE REVIEW

**Comment by Sajo811** [comment]
Not sure how to upload images to the `tree/master/images` directory, I think I can only do so with write access. This should work

**Comment by ZedPea** [comment]
To add images, fork the repository, clone it to your computer, drop the image, then `git add` it, `git commit`, and `git push`, then make a new PR.

You would want to do this on a branch so it doesn't conflict with your other changes - you can do that after `git clone` by doing `git branch somebranchname` then `git checkout somebranchname` to switch to that branch.

I'm not sure if it's possible to do so via the github UI, if you just make a straight fork you might be able to upload files, not sure.

**Comment by ZedPea** [comment]
Add the image to the PR and then we can link directly to it :)

**Comment by Sajo811** [comment]
Not sure what that means :/

Trying to make a PR from my fork and update the link to the old one, let me know if that works.

**Comment by Sajo811** [comment]
Added PR of deposit image from my fork-
Merged all commits from master branch here into mine, upload picture then made a pr of the whole `images` directory into here (i think).

Updated this link to redirect to what should be the location it will be at.

**Comment by ZedPea** [comment]
It's probably easier if you don't do changed via github as you can only make one file change at once, but this should work regardless

**Pull request merged**
